name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.before }} # Use the ref instead of the default branch

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"

      - name: Extract Version Name
        id: extract_version
        run: echo "::set-output name=version_name::$(grep -oP '(?<=versionName ").*(?=")' build.gradle)"

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK to Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: app/build/outputs/apk/release/OpenLinkClient-${{ steps.extract_version.outputs.version_name }}.apk
          asset_name: OpenLinkClient-${{ steps.extract_version.outputs.version_name }}.apk
          asset_content_type: application/vnd.android.package-archive
          distribution: "public"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
