name: Build and Release APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "19"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Build Project
        run: ./gradlew assembleRelease

      - name: Get Version Information
        id: get-version-info
        run: |
          VERSION_INFORMATION=$(./gradlew -q printVersionInformation)
          echo "version=$VERSION_INFORMATION" >> $GITHUB_OUTPUT

      - name: Create Release Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: create_tag
        run: |
          TAG_NAME="release-${{ steps.get-version-info.outputs.version }}-${{ github.sha }}"
          echo "release_tag=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.release_tag }}
          release_name: Release ${{ steps.get-version-info.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/OpenLinkClient-${{ steps.get-version-info.outputs.version }}.apk
          asset_name: OpenLinkClient-${{ steps.get-version-info.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive
