name: Build and Release APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GRADLE_USER_HOME: ${{ github.workspace }}/.gradle

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "19"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Project
        run: ./gradlew assembleRelease

      - name: Get Version Information
        id: version
        run: |
          VERSION=$(./gradlew -q printVersionInformation)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          TAG_NAME="release-${{ steps.version.outputs.version }}-${{ github.sha }}"
          echo "release_tag=$TAG_NAME" >> $GITHUB_ENV

      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.release_tag }}
          release_name: Release ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/OpenLinkClient-${{ steps.version.outputs.version }}.apk
          asset_name: OpenLinkClient-${{ steps.version.outputs.version }}.apk
          asset_content_type: application/vnd.android.package-archive
