name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  main_project_module: app
  playstore_name: nakrad

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21" # Use Java 21
          cache: "gradle"

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run gradle tests
        run: ./gradlew test

      - name: Build gradle project
        run: ./gradlew build

      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug
        uses: actions/upload-artifact@v3
        with:
          name: Debug-APK-${{ github.run_number }}
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release
        uses: actions/upload-artifact@v3
        with:
          name: Release-APK-${{ github.run_number }}
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v3
        with:
          name: Release-AAB-${{ github.run_number }}
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v3

      - name: Download Debug APK Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.workflow }}
          name: Debug-APK-${{ github.run_number }}
          path: downloads

      - name: Download Release APK Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.workflow }}
          name: Release-APK-${{ github.run_number }}
          path: downloads

      - name: Download Release AAB Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: ${{ github.workflow }}
          name: Release-AAB-${{ github.run_number }}
          path: downloads

      - name: Generate tag
        id: generate_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d%H%M%S')"

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.generate_tag.outputs.tag }}
          body: "Automated release ${{ steps.generate_tag.outputs.tag }}"
          draft: false
          prerelease: false
          tag_name: ${{ steps.generate_tag.outputs.tag }}
          files: downloads/*